import { createUseStyles } from "react-jss";

const useStyles = createUseStyles({
  continer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    width: "100vw",
    color: "white",
    gap: "1rem",
    padding: "1rem",
  },
  cardGrid: {
    display: "flex",
    flexDirection: "row",
    marginBottom: 'auto',
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 300,
    width: "80vw",
    color: "white",
    background: "rgba(0, 0, 0, 0.2)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    borderRadius: "10px",
    padding: 6,
  },
  card: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: 100,
    width: 100,
    margin: 12,
    background: "rgba(255, 255, 255, 0.4)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    borderRadius: "10px",
    cursor: "pointer",
    "&:hover": {
      background: "rgba(255, 255, 255, 0.6)",
    },
  },
  pageTttle: {
    fontSize: "2rem",
    marginBottom: "1rem",
  },
  cardBtn: {
    border: 'none',
    width: '100%',
    height: '100%',
    background: 'transparent',
    fontSize: 44,

    cursor: 'pointer',
    color: 'white',
    fontWeight: 'bold'
  },
  modal: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 20,
  },
  modalButton: {
    border: 'none',
    width: '100%',
    height: '100%',
    fontSize: 34,
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    borderRadius: '10px',
    cursor: 'pointer',
    color: 'white',
    fontWeight: 'bold',
    background: 'rgba(255, 255, 255, 0.1)',
    padding: 16,
    '&:hover': {
      background: 'rgba(255, 255, 255, 0.2)',
    },
  },
  backButton: {
    marginLeft: 'auto',
    marginBottom: 'auto',
    border: 'none',
    width: 80,
    height: 60,
    fontSize: 34,
    backdropFilter: 'blur(10px)',
    background: 'linear-gradient(135deg, rgba(255, 255, 255, 0.2) 0%, rgba(255, 0, 0, 0.3) 100%)',
    WebkitBackdropFilter: 'blur(10px)',
    borderRadius: '10px',
    cursor: 'pointer',
    color: 'white',
    fontWeight: 'bold',
    padding: 16,
    '&:hover': {
      background: 'linear-gradient(135deg, rgba(255, 255, 255, 0.2) 0%, rgba(255, 0, 0, 0.4) 100%)',
    },
  }
});

export default useStyles;
